networks:
  sermas_dev:
    external: true

services:
  kiosk:
    entrypoint: npm
    command: run dev
    environment:
      - BUILD_FROM_TS=${BUILD_FROM_TS}
    networks:
      default:
        aliases:
          - kiosk
          - sermas-toolkit-api-kiosk-1
      sermas_dev:
    build: .
    image: ghcr.io/sermas-eu/kiosk:dev
    volumes:
      - ./:/app
      - ../sermas-toolkit-web:/sermas-toolkit-web
